name: Build Python Wheels

on:
  push:

jobs:
  build_wheels:
    name: Build Wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install cibuildwheel

      - name: Build Wheel
        env:
          CIBW_BUILD: cp${{ matrix.python-version }}-*
          CIBW_SKIP: "*-musllinux_*"
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
